build:
	gcc -fopenmp -lm -o a.out PPD_PA2_B0829002_1.c
	gcc -fopenmp -lm -o b.out PPD_PA2_B0829002_2.c
	gcc -fopenmp -lm -o c.out PPD_PA2_B0829002_3.c
	gcc -fopenmp -lm -o d.out PPD_PA2_B0829002_4.c
clean:
	rm -f *.out